### ISSUE TITLE
I.E Disability Etiquette

### ISSUE THREAD

**Issue by CarlyGerard** [robfentress/cpacc-practice#42]
```

// Study task: I:D Apply disability etiquette to a specific scenario. Judge the appropriateness of various ways of referring to or about people with disabilities

// Sources:
// The [Certified Professional in Accessibility Core Competencies Body of Knowledge](https://iaap.membershipsoftware.org/files/IAAP%20CPACC%20BOK%202017_062317.docx)
// [Deque University: Talking about People with Disabilities](https://dequeuniversity.com/class/iaap-cpacc1/disability-etiquette/talking-about)

Which of the following is an example of "People First" language? 
{
  ~Crippled 
  ~The handicapped 
  =People who are blind 
  ~The blind
}

```

**Comment by robfentress** [comment]
Thanks for submitting your question! I adjusted the referenced study task to be little more specific to [the numbering system I've adopted](https://github.com/robfentress/cpacc-practice/blob/master/I/E/index.md).  If that change I made is okay, I'll go ahead and add it.  

Oh, I also wanted to make sure that this question isn't verbatim taken from the Deque University course, since that is copyrighted material.  Are we good there?

```
// Study task: I:E.1 Judge the appropriateness of various ways of referring to or about people with disabilities

// Sources:
// The [Certified Professional in Accessibility Core Competencies Body of Knowledge](https://iaap.membershipsoftware.org/files/IAAP%20CPACC%20BOK%202017_062317.docx)
// [Deque University: Talking about People with Disabilities](https://dequeuniversity.com/class/iaap-cpacc1/disability-etiquette/talking-about)

Which of the following is an example of "People First" language? 
{
  ~Crippled 
  ~The handicapped 
  =People who are blind 
  ~The blind
}
```

**Comment by robfentress** [comment]
Whoops!  Misnumbered the study task myself there. Changed it to I:E.2.

**Comment by CarlyGerard** [comment]
@robfentress It's not verbatim from Deque. There's a similar question in their quiz but it is specific to blindness and doesn't specifically mention the "People First" concept.

**Comment by robfentress** [comment]
Thanks, @CarlyGerard!  [Question added](https://github.com/robfentress/cpacc-practice/commit/ac957e43e0f26b1a26d6cb1116f739ba90b59a26).
