### ISSUE TITLE
What is the difference between age-related disabilities and temporary disabilities?

### ISSUE THREAD

**Issue by SpuddyAT** [robfentress/cpacc-practice#45]
// Study task: I:B.2 Classify specific conditions under their relevant disability category or categories.

// Sources:
// The [IAAP CPACC Certification Preparation]
(https://dequeuniversity.com/class/iaap-cpacc1/basic-concepts/our-diverse-abilities)

What is the answer to this practice question?
{
  ~Temporary disabilities are long term and age-related are short term 
  ~Temporary disabilities cannot be accommodated and age-related can be accommodated
  =Temporary disabilities are short term and age-related disabilities are long term
  ~Temporary disabilities can be accommodated and age-related cannot be accommodated
}

**Comment by robfentress** [comment]
Thanks for submitting, @SpuddyAT.  I've added your question.
